config/routes.rb
Rails.application.routes.draw do
  resources :contents, param: :slug do
    post ":category_slug", to: "contents#add_category", as: "add_category"
    delete ":category_slug", to: "contents#remove_category", as: "remove_category"
  end
  resources :categories, param: :slug
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "contents#index"
end

app/models/content.rb
class Content < ApplicationRecord
  include Uuid
  include Slugable

  belongs_to :user
  belongs_to :content_type
  has_and_belongs_to_many :categories, join_table: :contents_categories

  has_rich_text :body
  has_many_attached :attachements

  validates :title, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :description, presence: true, uniqueness: true, length: { maximum: 255 }

  def to_param
    self.slug
  end

  def can_update?
    self.user == Current.user
  end

end

app/models/content_type.rb
class ContentType < ApplicationRecord
  include Uuid
  include Slugable

  has_many :contents

  validates :title, presence: true, uniqueness: true, length: { maximum: 255 }

  def to_param
    self.slug
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]
  before_action :verify_update, only: %i[ edit update destroy ]

  # GET /contents or /contents.json
  def index
    @contents = Content

    if params[:q].present?
      @contents = @contents.where(
      "contents.title LIKE :search OR contents.description LIKE :search",
        search: "%#{Content.sanitize_sql_like(params[:q])}%"
      )
    end

    if params[:c].present? && params[:c].strip != ""
      slugs = params[:c].split(' ')
      category_ids = Category.where(slug: slugs).pluck(:id)
      if category_ids.any?
        @contents = @contents
          .joins(:categories)
          .where(categories: { id: category_ids })
          .group('contents.id')
          .having('COUNT(DISTINCT categories.id) = ?', category_ids.size)
    end
  end

  # Add explicit select for grouped results:
  @contents = @contents.select('contents.*').order(updated_at: :desc)
  # Convert data to integer
  @contents_count = (@contents.size.is_a?(Hash)) ? @contents.size.size.to_i : @contents.size.to_i
  end

  # GET /contents/1 or /contents/1.json
  def show
    @categories = Category.where.not(id: @content.category_ids)
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)
    @content.user = Current.user

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to @content, notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy!

    respond_to do |format|
      format.html { redirect_to contents_path, status: :see_other, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_category
    @content = Content.find_by(slug: params.expect(:content_slug))

    verify_update

    @category = Category.find_by(slug: params.expect(:category_slug))
    @content.categories << @category

    redirect_to @content, notice: "The category was successfully added."
  end

  def remove_category
    @content = Content.find_by(slug: params.expect(:content_slug))

    verify_update

    @category = Category.find_by(slug: params.expect(:category_slug))
    @content.categories.delete(@category)

    redirect_to @content, notice: "The category was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find_by(slug: params.expect(:slug))
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.expect(content: [ :slug, :content_type_id, :title, :description, :body, :attachements ])
    end

    def verify_update
      if !@content.can_update?
        # render :show, status: :unauthorized
        redirect_to @content
      end
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<div class="content">
  <div class="title"><%= link_to content.title, content %></div>
  <div>
    <%= content.description %>
  </div>
  <%# content.content_type.title %>
</div>

app/views/contents/_form.html.erb
<div class="form">
  <%= form_with(model: content) do |form| %>
    <% if content.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

        <ul>
          <% content.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :slug, style: "display: block" %>
      <%= form.text_field :slug %>
    </div>

    <div>
      <%= form.label :title, style: "display: block" %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_field :description %>
    </div>

    <div>
      <%= form.label :content_type_id, style: "display: block" %>
      <%= form.collection_select :content_type_id, ContentType.all, :id, :title, { prompt: "Choose content type" } %>
    </div>

    <div>
      <%= form.label :body, style: "display: block" %>
      <%= form.rich_text_area :body %>
    </div>

    <div>
      <%= form.label :attachements, style: "display: block" %>
      <%= form.file_field :attachements %>
    </div>

    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/contents/edit.html.erb
<% content_for :title, "Editing content" %>

<h1>Editing content</h1>

<%= render "form", content: @content %>

<br>

<div class="actions">
  <div class="row">
    <%= link_to "Show this content", @content %>
    <%= link_to "Back to contents", contents_path %>
  </div>
</div>

app/views/contents/index.html.erb
<% content_for :title, "Contents" %>
<p style="color: green"><%= notice %></p>

<h1>Contents (<%= @contents_count %>)</h1>

<div class="searchbar">
  <%= form_with url: contents_path, method: :get, local: true do |f| %>
    <%= f.text_field :q, placeholder: "Search contents...", value: params[:q] %>
    <%= f.text_field :c, placeholder: "Categories...", value: params[:c] %>
    <%= image_submit_tag("icons/search.svg", alt: "Search") %>
  <% end %>
</div>

<% if @contents_count > 19 %>
  <div class="add-item">
    <%= link_to "New content", new_content_path %>
  </div>
<% end %>

<div id="contents">
  <% @contents.each do |content| %>
    <%= render content %>
  <% end %>
</div>

<div class="add-item">
  <%= link_to "New content", new_content_path %>
</div>

app/views/contents/new.html.erb
<% content_for :title, "New content" %>

<h1>New content</h1>

<%= render "form", content: @content %>

<br>

<div class="actions">
  <div class=row>
    <%= link_to "Back to contents", contents_path %>
  </div>
</div>

app/views/contents/show.html.erb
<% content_for :title, @content.title %>

<div id="content">
  <p style="color: green"><%= notice %></p>

  <div class=show>
    <%= @content.content_type.title %>

    <div class=title><%= @content.title %></div>
    <div class="body"><%= @content.body %></div>
  </div>

  <% if @content.can_update? %>
    <div class="actions">
      <div class="row">
        <%= link_to "Edit this content", edit_content_path(@content) %>
        <%= link_to "Back to contents", contents_path %>
      </div>

      <div class="delete">
        <%# button_to "Destroy this content", @content, method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to "Destroy this content", @content, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
      </div>
    </div>

    <div>
      Remove categories:
      <% @content.categories.each do |category| %>
        <%= button_to category.title, content_remove_category_path(@content, category), method: :delete, data: { confirm: "Are you sure?" } %>
      <% end %>
    </div>

    <div>
      Add categories:
      <% @categories.each do |category| %>
        <%= button_to category.title, content_add_category_path(@content, category), method: :post %>
      <% end %>
    </div>
  <% else %>
    <div class="actions">
      <div class="row">
        <%= link_to "Back to contents", contents_path %>
      </div>
    </div>
  <% end %>
</div>