config/routes.rb
Rails.application.routes.draw do
  resources :contents, param: :slug do
    post ":category_slug", to: "contents#add_category", as: "add_category"
    delete ":category_slug", to: "contents#remove_category", as: "remove_category"
  end
  resources :categories, param: :slug
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "contents#index"
end

app/views/layouts/_header.html.erb
<div id="topnav">
  <% if current_page?(root_path) || request.original_url.include?(contents_path) %>
    <%= link_to "Contents", root_path, class: "active" %>
  <% else %>
    <%= link_to "Contents", root_path %>
  <% end %>

  <% if request.original_url.include?(categories_path) %>
    <%= link_to "Categories", categories_path, class: "active" %>
  <% else %>
    <%= link_to "Categories", categories_path %>
  <% end %>

  <% if authenticated? %>
    <%= link_to "Log out", session_path, class: "right", data: { turbo_method: :delete } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Knowledge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <!-- <link rel="icon" href="/icon.svg" type="image/svg+xml"> -->
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if authenticated? %>
      <%= render "layouts/header" %>
    <% end %>
    <div id="main">
      <%= yield %>
    </div>
  </body>
</html>